// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://pvpwkzjhybrtetalzdep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2cHdrempoeWJydGV0YWx6ZGVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NzExOTQsImV4cCI6MjA3MTU0NzE5NH0.QivP2Na4LXGwB90R72-rB5IDN3Cs42qVeEbwLbufqZE";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
